import { CdpClient } from "./cdp/client.ts";
import { type BrowserSettings } from "./remote-login.ts";
import { type LiveSessionVerifier } from "./live-auth-verifier.ts";
import { type SpawnedBrowserProcess } from "./process-manager.ts";
import type { BrowserInfo, BrowserPlatform, BrowserRunMode, BrowserSessionStatus, CdpPageLease, NativeBrowserRuntime } from "./types.ts";
export type ProcessLauncher = (browser: BrowserInfo, profileDir: string, initialUrl?: string, minimized?: boolean, headless?: boolean) => Promise<SpawnedBrowserProcess>;
export type CdpClientFactory = (port: number, signal?: AbortSignal) => Promise<CdpClient>;
export type PidChecker = (pid: number) => boolean;
export type PidKiller = (pid: number) => void;
export declare class SessionManager implements NativeBrowserRuntime {
    private records;
    private profileStore;
    private stateStore;
    private readonly browserChoice;
    private readonly idleShutdownMs;
    private readonly launcher;
    private readonly cdpFactory;
    private readonly isPidAliveFn;
    private readonly killPidFn;
    private readonly liveSessionVerifier;
    private readonly readBrowserSettings;
    private disposed;
    constructor(browserChoice?: string | (() => string), baseDirOverride?: string, idleShutdownMs?: number, launcher?: ProcessLauncher, cdpFactory?: CdpClientFactory, isPidAliveFn?: PidChecker, killPidFn?: PidKiller, liveSessionVerifier?: LiveSessionVerifier, readBrowserSettings?: () => BrowserSettings);
    private getRecord;
    private enqueue;
    detect(): Promise<BrowserInfo | null>;
    checkAuthentication(platform: BrowserPlatform): Promise<boolean>;
    verifyAuthenticationForOperation(platform: BrowserPlatform, signal?: AbortSignal, mode?: BrowserRunMode): Promise<boolean>;
    private internalCheckAuth;
    private hasRequiredCookies;
    status(platform: BrowserPlatform): Promise<BrowserSessionStatus>;
    private sessionStatus;
    /** Report the current browser without applying an obsolete authentication probe. */
    private unverifiedStatus;
    login(platform: BrowserPlatform, signal?: AbortSignal): Promise<BrowserSessionStatus>;
    private runLogin;
    private prepareInteractiveLogin;
    startRemoteLogin(platform: BrowserPlatform): Promise<import("../../shared/remote-login.ts").RemoteLoginView>;
    private remoteSession;
    remoteLoginFrame(platform: BrowserPlatform, id: string): Promise<import("../../shared/remote-login.ts").RemoteLoginView>;
    remoteLoginInput(platform: BrowserPlatform, id: string, input: unknown): Promise<void>;
    closeRemoteLogin(platform: BrowserPlatform, id: string): Promise<void>;
    openPage(platform: BrowserPlatform, url: string, signal?: AbortSignal, mode?: BrowserRunMode): Promise<CdpPageLease>;
    createPage(platform: BrowserPlatform, signal?: AbortSignal, mode?: BrowserRunMode): Promise<CdpPageLease>;
    private retainLease;
    private releaseLease;
    private scheduleIdleTimer;
    private acquireSession;
    private internalStop;
    stop(platform: BrowserPlatform): Promise<void>;
    resetSession(platform: BrowserPlatform): Promise<void>;
    dispose(): Promise<void>;
}
